trigger: none

stages:
- stage: build
  pool:
    vmImage: ubuntu-latest
  jobs:
  - job: build
    steps:
      - checkout: self

      - template: ../templates/steps/copy_files_build_image.yaml
        parameters:
          container_registry: 'compregistrydevcr'
          image_repository_name: 'frontend'
