# call template with jobs in a stage

trigger: none

stages:
- stage: build
  pool:
    vmImage: ubuntu-latest
  jobs:
  - template: ../templates/jobs/build_app.yml
    parameters:
      container_registry: 'compregistrydevcr'
      image_repository_name: 'frontend'
