parameters:
- name: container_registry
- name: image_repository_name

jobs:
- job: build_windows
  dependsOn: []
  pool:
    vmImage: windows-latest
  steps:
  - template: ../steps/build_app.yml
    parameters:
      container_registry: ${{ parameters.container_registry }}
      image_repository_name: ${{ parameters.image_repository_name }}

- job: build_linux
  dependsOn: []
  pool:
    vmImage: ubuntu-latest
  steps:
  - template: ../steps/build_app.yml
    parameters:
      container_registry: ${{ parameters.container_registry }}
      image_repository_name: ${{ parameters.image_repository_name }}

- job: build_macos
  dependsOn: []
  pool:
    vmImage: macOS-latest
  steps:
  - template: ../steps/build_app.yml
    parameters:
      container_registry: ${{ parameters.container_registry }}
      image_repository_name: ${{ parameters.image_repository_name }}
