name: Template Call

on:
  workflow_dispatch:

jobs:
  build:
    uses: chrburmeister/azure-pipelines-to-github-actions/.github/workflows/template_steps_part1.yml@main
    with:
      container_registry: 'compregistrydevcr'
      image_repository_name: 'frontend'
      password: ${{ secrets.PASSWORD }}
  deploy:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - shell: pwsh
        run: |
          Write-Output "deploy to Azure!"
